tools:
    external_code_coverage:
        timeout: 600
checks:
    php:
         verify_property_names: true
         verify_access_scope_valid: true
         verify_argument_usable_as_reference: true
         useless_calls: true
         use_statement_alias_conflict: true
         unused_properties: true
         unused_parameters: true
         unused_methods: true
         unreachable_code: true
         too_many_arguments: true
         sql_injection_vulnerabilities: true
         switch_fallthrough_commented: true
         security_vulnerabilities: true
         simplify_boolean_return: true
         return_doc_comments: true
         require_php_tag_first: true
         property_assignments: true
         precedence_in_conditions: true
         precedence_mistakes: true
         phpunit_assertions: true
         parse_doc_comments: true
         parameter_doc_comments: true
         param_doc_comment_if_not_inferrable: true
         non_commented_empty_catch_block: true
         no_trailing_whitespace: true
         no_short_variable_names:
             minimum: '3'
         no_short_open_tag: true
         no_non_implemented_abstract_methods: true
         no_long_variable_names:
             maximum: '20'
         no_goto: true
         no_exit: true
         no_eval: true
         no_debug_code: true
         check_method_contracts:
             verify_interface_like_constraints: true
             verify_documented_constraints: true
             verify_parent_constraints: true
         return_doc_comment_if_not_inferrable: true
build:
     nodes:
        php71:
            environment:
                php: 7.1
     tests:
        override:
            - true
#        analysis:
#            tests:
#                override:
#                     - eslint-run "resources/assets/js/**"
#                     - jshint-run
#                     -
#                        command: phpcs-run
#                        use_website_config: true
#                     - php-scrutinizer-run
#                     - vendor/bin/codecept run -c tests/Codeception