language: php

php:
  - 7.1
  - 7.2

addons:
  hosts:
  - dcas-laravel55.dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $COMPOSER_FLAGS == '' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

before_install:
  - sudo apt-get -qq update
  - mysql -e 'CREATE DATABASE dcas_l55_refactor;'


before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - travis_retry composer self-update
  - travis_retry composer install --dev --prefer-source --no-interaction
  - npm install
  - php artisan migrate
  - node_modules/.bin/bower update

branches:
  only:
  - master
  - /^deploy-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

notifications:
  email:
    recipients:
      - sarah@sarahrenner.work
      - sarahalexandrarenner@icloud.com
    on_success: change
    on_failure: always

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/phpspec/phpspec/bin/phpspec run
  - vendor/bin/behat
  - vendor/bin/codecept run -c tests/Codeception

services:
  - mysql
  - redis
  - sqlite3

sudo: required
