branches:
  only:
  - master
  - /^deploy-.*$/

notifications:
  email:
    recipients:
      - sarah@sarahrenner.work
      - sarahalexandrarenner@icloud.com
    on_success: change
    on_failure: always

addons:
  hosts:
  - dcas-laravel55.dev

language: php

sudo: required

php:
  - 7.1.8

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_install:
  - sudo apt-get -qq update
  - mysql -e 'CREATE DATABASE dcas_l55_refactor;'


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --prefer-source --no-interaction
  - npm install
  - php artisan migrate
  - node_modules/.bin/bower update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/phpspec/phpspec/bin/phpspec run
  - vendor/bin/behat

services:
  - mysql
  - redis
  - sqlite3

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $COMPOSER_FLAGS == '' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi