language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

addons:
  hosts:
  - dcas-laravel55.dev

branches:
  only:
  - master
  - /^deploy-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

env:
  global:
    - setup=stable

before_install:
  - sudo apt-get -qq update
  - mysql -e 'CREATE DATABASE dcas_l55_refactor;'
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --dev --prefer-source --no-interaction
  - npm install
  - php artisan migrate
  - node_modules/.bin/bower update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/phpspec/phpspec/bin/phpspec run
  - vendor/bin/behat
  - vendor/bin/codecept run -c tests/Codeception

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $COMPOSER_FLAGS == '' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

notifications:
  email:
    recipients:
      - sarah@sarahrenner.work
      - sarahalexandrarenner@icloud.com
    on_success: change
    on_failure: always

services:
  - memcached
  - mysql
  - redis-server
  - sqlite3

sudo: false
